input = input("Do you like sports? Y/N")
if input = "Y":     # I hate sports.
	print("""I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
		I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports
	I hate sports""")
elif input = "N":
	print("Good. I hate sports")
else:
	print("Huh? Try again.")